@extends('errors.layout')
@section('title', __('Sin permiso'))
@section('code', '403')
@section('heading', __('No tenés acceso a esta sección'))
@section('message', __('Si creés que deberías tenerlo, pedile acceso al administrador del sistema.'))
