@extends('errors.layout')
@section('title', __('Sesión expirada'))
@section('code', '419')
@section('heading', __('Tu sesión expiró'))
@section('message', __('Por seguridad cerramos la sesión tras un rato de inactividad. Volvé a entrar y repetí la acción.'))
