@extends('errors.layout')
@section('title', __('Demasiados intentos'))
@section('code', '429')
@section('heading', __('Demasiados intentos seguidos'))
@section('message', __('Esperá unos segundos y volvé a intentarlo.'))
